name: AlexxAutoWarn
version: '1.0.0'
main: net.alexxiconify.alexxAutoWarn.AlexxAutoWarn
api-version: '1.21'
author: Alexxiconify
description: A modernized zone protection plugin.
softdepend: [ CoreProtect ]
commands:
  autowarn:
    description: Main command for the AutoWarn plugin.
    usage: /<command> [subcommand] [args]
    aliases: [ aw ]
    permission: autowarn.admin.use
permissions:
  autowarn.admin.*:
    description: Grants access to all admin commands.
    children:
      autowarn.admin.use: true
      autowarn.admin.wand: true
      autowarn.admin.define: true
      autowarn.admin.remove: true
      autowarn.admin.list: true
      autowarn.admin.info: true
      autowarn.admin.setaction: true
      autowarn.admin.reload: true
      autowarn.admin.banned: true
  autowarn.bypass:
    description: Bypasses all zone restrictions.
    default: op
  autowarn.notify:
    description: Receives alerts for actions in zones.
    default: op